LuaExcelManager = LuaExcelManager or {}

LuaExcelManager.param_Common = {
	Map_Width = 288,
	Map_Height = 288,
	CameraDistance_Z = 10,
	CameraChangeFactor_Z = 4,
	LimitRadius = 100,
	CameraDistance_Y = 8,
	CameraChangeFactor_Y = 1.5,
}

LuaExcelManager.param_SnowBallBasic = {
	PlaneRadius = 1.2,
	CircleNum_N = 7,
	CircleNum_B = -1,
	Split_K = 3,
	Split_N = 10,
	Split_CanSplitMass = 9.6,
	Split_Max = 16,
	Split_RelStartPos = 0,
	Split_RelDist = 27,
	Split_ServerOffSet = 50,
	Merge_ContactTime = 12,
	Merge_CoolTime = 1,
	Merge_Range = 5,
	Merge_SpeedFactor = 5,
	Emit_SnowMass = 3.6,
	Emit_CanEmitSnowMass = 9.6,
	Emit_RelStartPos = 0,
	Emit_RelDist = 27,
	Emit_S = 1,
	Emit_A = 1,
	Emit_L = 1,
	Emit_Interval = 0.05,
	Emit_ServerOffSet = 50,
	Attack_Factor = 1.2,
	Attack_A = 2,
	SlowMoveSpeed = 0,
	ScaleSpeed = 0,
	shot_minseconds = 0.5,
	shot_maxseconds = 1.5,
	shot_add_coef = 0.01,
	shot_delayseconds = 0.2,
	split_cd = 0.1,
	split_speed_factor = 1.75,
	split_last_seconds = 2,
}
