LuaExcelManager = LuaExcelManager or {}

LuaExcelManager.scene_plane = {
	[1]={ID = 1,Path = [[Planes/Plane_1/plane1_1.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[2]={ID = 2,Path = [[Planes/Plane_1/plane1_2.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[3]={ID = 3,Path = [[Planes/Plane_1/plane1_3.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[4]={ID = 4,Path = [[Planes/Plane_1/plane1_4.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[5]={ID = 5,Path = [[Planes/Plane_1/plane1_5.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[6]={ID = 6,Path = [[Planes/Plane_1/plane1_6.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[7]={ID = 7,Path = [[Planes/Plane_1/plane1_7.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[8]={ID = 8,Path = [[Planes/Plane_1/plane1_8.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[9]={ID = 9,Path = [[Planes/Plane_1/plane1_9.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[10]={ID = 10,Path = [[Planes/Plane_1/plane1_10.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[11]={ID = 11,Path = [[Planes/Plane_2/plane2_1.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[12]={ID = 12,Path = [[Planes/Plane_2/plane2_2.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[13]={ID = 13,Path = [[Planes/Plane_2/plane2_3.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[14]={ID = 14,Path = [[Planes/Plane_2/plane2_4.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[15]={ID = 15,Path = [[Planes/Plane_2/plane2_5.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[16]={ID = 16,Path = [[Planes/Plane_2/plane2_6.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[17]={ID = 17,Path = [[Planes/Plane_2/plane2_7.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[18]={ID = 18,Path = [[Planes/Plane_2/plane2_8.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[19]={ID = 19,Path = [[Planes/Plane_2/plane2_9.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[20]={ID = 20,Path = [[Planes/Plane_2/plane2_10.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[21]={ID = 21,Path = [[Planes/Plane_3/plane3_1.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[22]={ID = 22,Path = [[Planes/Plane_3/plane3_2.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[23]={ID = 23,Path = [[Planes/Plane_3/plane3_3.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[24]={ID = 24,Path = [[Planes/Plane_3/plane3_4.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[25]={ID = 25,Path = [[Planes/Plane_3/plane3_5.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[26]={ID = 26,Path = [[Planes/Plane_3/plane3_6.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[27]={ID = 27,Path = [[Planes/Plane_3/plane3_7.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[28]={ID = 28,Path = [[Planes/Plane_3/plane3_8.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[29]={ID = 29,Path = [[Planes/Plane_3/plane3_9.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[30]={ID = 30,Path = [[Planes/Plane_3/plane3_10.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[31]={ID = 31,Path = [[Planes/Plane_4/plane4_1.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[32]={ID = 32,Path = [[Planes/Plane_4/plane4_2.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[33]={ID = 33,Path = [[Planes/Plane_4/plane4_3.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[34]={ID = 34,Path = [[Planes/Plane_4/plane4_4.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[35]={ID = 35,Path = [[Planes/Plane_4/plane4_5.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[36]={ID = 36,Path = [[Planes/Plane_4/plane4_6.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[37]={ID = 37,Path = [[Planes/Plane_4/plane4_7.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[38]={ID = 38,Path = [[Planes/Plane_4/plane4_8.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[39]={ID = 39,Path = [[Planes/Plane_4/plane4_9.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[40]={ID = 40,Path = [[Planes/Plane_4/plane4_10.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[41]={ID = 41,Path = [[Planes/Plane_5/zhandouji_1.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[42]={ID = 42,Path = [[Planes/Plane_5/zhandouji_2.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[43]={ID = 43,Path = [[Planes/Plane_5/zhandouji_3.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[44]={ID = 44,Path = [[Planes/Plane_5/zhandouji_4.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[45]={ID = 45,Path = [[Planes/Plane_5/zhandouji_5.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[46]={ID = 46,Path = [[Planes/Plane_5/zhandouji_6.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[47]={ID = 47,Path = [[Planes/Plane_5/zhandouji_7.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[48]={ID = 48,Path = [[Planes/Plane_5/zhandouji_8.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[49]={ID = 49,Path = [[Planes/Plane_5/zhandouji_9.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[50]={ID = 50,Path = [[Planes/Plane_5/zhandouji_10.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[51]={ID = 51,Path = [[Planes/Plane_6/yuanzhanji_1.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[52]={ID = 52,Path = [[Planes/Plane_6/yuanzhanji_2.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[53]={ID = 53,Path = [[Planes/Plane_6/yuanzhanji_3.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[54]={ID = 54,Path = [[Planes/Plane_6/yuanzhanji_4.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[55]={ID = 55,Path = [[Planes/Plane_6/yuanzhanji_5.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[56]={ID = 56,Path = [[Planes/Plane_6/yuanzhanji_6.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[57]={ID = 57,Path = [[Planes/Plane_6/yuanzhanji_7.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[58]={ID = 58,Path = [[Planes/Plane_6/yuanzhanji_8.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[59]={ID = 59,Path = [[Planes/Plane_6/yuanzhanji_9.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[60]={ID = 60,Path = [[Planes/Plane_6/yuanzhanji_10.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[61]={ID = 61,Path = [[Planes/Plane_7/maotouying_1.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[62]={ID = 62,Path = [[Planes/Plane_7/maotouying_2.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[63]={ID = 63,Path = [[Planes/Plane_7/maotouying_3.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[64]={ID = 64,Path = [[Planes/Plane_7/maotouying_4.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[65]={ID = 65,Path = [[Planes/Plane_7/maotouying_5.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[66]={ID = 66,Path = [[Planes/Plane_7/maotouying_6.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[67]={ID = 67,Path = [[Planes/Plane_7/maotouying_7.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[68]={ID = 68,Path = [[Planes/Plane_7/maotouying_8.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[69]={ID = 69,Path = [[Planes/Plane_7/maotouying_9.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[70]={ID = 70,Path = [[Planes/Plane_7/maotouying_10.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[71]={ID = 71,Path = [[Planes/Plane_8/jiqiwazhanji_1.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[72]={ID = 72,Path = [[Planes/Plane_8/jiqiwazhanji_2.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[73]={ID = 73,Path = [[Planes/Plane_8/jiqiwazhanji_3.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[74]={ID = 74,Path = [[Planes/Plane_8/jiqiwazhanji_4.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[75]={ID = 75,Path = [[Planes/Plane_8/jiqiwazhanji_5.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[76]={ID = 76,Path = [[Planes/Plane_8/jiqiwazhanji_6.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[77]={ID = 77,Path = [[Planes/Plane_8/jiqiwazhanji_7.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[78]={ID = 78,Path = [[Planes/Plane_8/jiqiwazhanji_8.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[79]={ID = 79,Path = [[Planes/Plane_8/jiqiwazhanji_9.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[80]={ID = 80,Path = [[Planes/Plane_8/jiqiwazhanji_10.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[81]={ID = 81,Path = [[Planes/Plane_9/jiqiren_1.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[82]={ID = 82,Path = [[Planes/Plane_9/jiqiren_2.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[83]={ID = 83,Path = [[Planes/Plane_9/jiqiren_3.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[84]={ID = 84,Path = [[Planes/Plane_9/jiqiren_4.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[85]={ID = 85,Path = [[Planes/Plane_9/jiqiren_5.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[86]={ID = 86,Path = [[Planes/Plane_9/jiqiren_6.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[87]={ID = 87,Path = [[Planes/Plane_9/jiqiren_7.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[88]={ID = 88,Path = [[Planes/Plane_9/jiqiren_8.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[89]={ID = 89,Path = [[Planes/Plane_9/jiqiren_9.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[90]={ID = 90,Path = [[Planes/Plane_9/jiqiren_10.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[91]={ID = 91,Path = [[Planes/Plane_10/duyanguai_1.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[92]={ID = 92,Path = [[Planes/Plane_10/duyanguai_2.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[93]={ID = 93,Path = [[Planes/Plane_10/duyanguai_3.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[94]={ID = 94,Path = [[Planes/Plane_10/duyanguai_4.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[95]={ID = 95,Path = [[Planes/Plane_10/duyanguai_5.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[96]={ID = 96,Path = [[Planes/Plane_10/duyanguai_6.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[97]={ID = 97,Path = [[Planes/Plane_10/duyanguai_7.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[98]={ID = 98,Path = [[Planes/Plane_10/duyanguai_8.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[99]={ID = 99,Path = [[Planes/Plane_10/duyanguai_9.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[100]={ID = 100,Path = [[Planes/Plane_10/duyanguai_10.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[101]={ID = 101,Path = [[Planes/Plane_11/zhifeiji_1.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[102]={ID = 102,Path = [[Planes/Plane_11/zhifeiji_2.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[103]={ID = 103,Path = [[Planes/Plane_11/zhifeiji_3.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[104]={ID = 104,Path = [[Planes/Plane_11/zhifeiji_4.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[105]={ID = 105,Path = [[Planes/Plane_11/zhifeiji_5.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[106]={ID = 106,Path = [[Planes/Plane_11/zhifeiji_6.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[107]={ID = 107,Path = [[Planes/Plane_11/zhifeiji_7.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[108]={ID = 108,Path = [[Planes/Plane_11/zhifeiji_8.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[109]={ID = 109,Path = [[Planes/Plane_11/zhifeiji_9.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[110]={ID = 110,Path = [[Planes/Plane_11/zhifeiji_10.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[111]={ID = 111,Path = [[Planes/Plane_12/zhanji_1.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[112]={ID = 112,Path = [[Planes/Plane_12/zhanji_2.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[113]={ID = 113,Path = [[Planes/Plane_12/zhanji_3.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[114]={ID = 114,Path = [[Planes/Plane_12/zhanji_4.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[115]={ID = 115,Path = [[Planes/Plane_12/zhanji_5.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[116]={ID = 116,Path = [[Planes/Plane_12/zhanji_6.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[117]={ID = 117,Path = [[Planes/Plane_12/zhanji_7.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[118]={ID = 118,Path = [[Planes/Plane_12/zhanji_8.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[119]={ID = 119,Path = [[Planes/Plane_12/zhanji_9.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[120]={ID = 120,Path = [[Planes/Plane_12/zhanji_10.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[121]={ID = 121,Path = [[Planes/Plane_13/mengji_1.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[122]={ID = 122,Path = [[Planes/Plane_13/mengji_2.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[123]={ID = 123,Path = [[Planes/Plane_13/mengji_3.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[124]={ID = 124,Path = [[Planes/Plane_13/mengji_4.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[125]={ID = 125,Path = [[Planes/Plane_13/mengji_5.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[126]={ID = 126,Path = [[Planes/Plane_13/mengji_6.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[127]={ID = 127,Path = [[Planes/Plane_13/mengji_7.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[128]={ID = 128,Path = [[Planes/Plane_13/mengji_8.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[129]={ID = 129,Path = [[Planes/Plane_13/mengji_9.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[130]={ID = 130,Path = [[Planes/Plane_13/mengji_10.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[131]={ID = 131,Path = [[Planes/Plane_14/moyu_1.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[132]={ID = 132,Path = [[Planes/Plane_14/moyu_2.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[133]={ID = 133,Path = [[Planes/Plane_14/moyu_3.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[134]={ID = 134,Path = [[Planes/Plane_14/moyu_4.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[135]={ID = 135,Path = [[Planes/Plane_14/moyu_5.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[136]={ID = 136,Path = [[Planes/Plane_14/moyu_6.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[137]={ID = 137,Path = [[Planes/Plane_14/moyu_7.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[138]={ID = 138,Path = [[Planes/Plane_14/moyu_8.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[139]={ID = 139,Path = [[Planes/Plane_14/moyu_9.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[140]={ID = 140,Path = [[Planes/Plane_14/moyu_10.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[141]={ID = 141,Path = [[Planes/Plane_15/xiazhanji_1.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[142]={ID = 142,Path = [[Planes/Plane_15/xiazhanji_2.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[143]={ID = 143,Path = [[Planes/Plane_15/xiazhanji_3.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[144]={ID = 144,Path = [[Planes/Plane_15/xiazhanji_4.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[145]={ID = 145,Path = [[Planes/Plane_15/xiazhanji_5.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[146]={ID = 146,Path = [[Planes/Plane_15/xiazhanji_6.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[147]={ID = 147,Path = [[Planes/Plane_15/xiazhanji_7.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[148]={ID = 148,Path = [[Planes/Plane_15/xiazhanji_8.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[149]={ID = 149,Path = [[Planes/Plane_15/xiazhanji_9.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[150]={ID = 150,Path = [[Planes/Plane_15/xiazhanji_10.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[151]={ID = 151,Path = [[Planes/Plane_16/dabai_1.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[152]={ID = 152,Path = [[Planes/Plane_16/dabai_2.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[153]={ID = 153,Path = [[Planes/Plane_16/dabai_3.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[154]={ID = 154,Path = [[Planes/Plane_16/dabai_4.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[155]={ID = 155,Path = [[Planes/Plane_16/dabai_5.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[156]={ID = 156,Path = [[Planes/Plane_16/dabai_6.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[157]={ID = 157,Path = [[Planes/Plane_16/dabai_7.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[158]={ID = 158,Path = [[Planes/Plane_16/dabai_8.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[159]={ID = 159,Path = [[Planes/Plane_16/dabai_9.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
	[160]={ID = 160,Path = [[Planes/Plane_16/dabai_10.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
}

LuaExcelManager.scene_bullet = {
	[20001]={ID = 20001,Path = [[Planes/CartoonPlanes/bullet_3.png]],},
	[20002]={ID = 20002,Path = [[Planes/CartoonPlanes/bullet_4.png]],},
	[20003]={ID = 20003,Path = [[Planes/CartoonPlanes/bullet_5.png]],},
	[20004]={ID = 20004,Path = [[Planes/CartoonPlanes/bullet_6.png]],},
	[20005]={ID = 20005,Path = [[Planes/CartoonPlanes/bullet_7.png]],},
	[20006]={ID = 20006,Path = [[Planes/CartoonPlanes/bullet_8.png]],},
	[20007]={ID = 20007,Path = [[Planes/CartoonPlanes/bullet_9.png]],},
	[20008]={ID = 20008,Path = [[Planes/CartoonPlanes/bullet_10.png]],},
	[20009]={ID = 20009,Path = [[Planes/CartoonPlanes/bullet_11.png]],},
	[20010]={ID = 20010,Path = [[Planes/CartoonPlanes/bullet_12.png]],},
	[20011]={ID = 20011,Path = [[Planes/CartoonPlanes/bullet_13.png]],},
	[20012]={ID = 20012,Path = [[Planes/CartoonPlanes/bullet_14.png]],},
	[20013]={ID = 20013,Path = [[Planes/CartoonPlanes/bullet_15.png]],},
	[20014]={ID = 20014,Path = [[Planes/CartoonPlanes/bullet_16.png]],},
	[20015]={ID = 20015,Path = [[Planes/CartoonPlanes/bullet_17.png]],},
	[20016]={ID = 20016,Path = [[Planes/CartoonPlanes/bullet_18.png]],},
	[20017]={ID = 20017,Path = [[Planes/CartoonPlanes/bullet_19.png]],},
	[20018]={ID = 20018,Path = [[Planes/CartoonPlanes/bullet_20.png]],},
	[20019]={ID = 20019,Path = [[Planes/CartoonPlanes/bullet_21.png]],},
}

LuaExcelManager.scene_SnowBlocks = {
	[1]={ID = 1,Path = [[Planes/CartoonPlanes/Energy.png]],},
}

LuaExcelManager.scene_darkplane = {
	[1]={ID = 1,Path = [[Planes/AbandonPlanes/plane1.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[2]={ID = 2,Path = [[Planes/AbandonPlanes/plane2.png]],Shadow = [[Planes/Shadow/plane2_shadow.png]],},
	[3]={ID = 3,Path = [[Planes/AbandonPlanes/plane3.png]],Shadow = [[Planes/Shadow/plane3_shadow.png]],},
	[4]={ID = 4,Path = [[Planes/AbandonPlanes/plane4.png]],Shadow = [[Planes/Shadow/plane1_shadow.png]],},
	[5]={ID = 5,Path = [[Planes/AbandonPlanes/plane5.png]],Shadow = [[Planes/Shadow/plane5_shadow.png]],},
	[6]={ID = 6,Path = [[Planes/AbandonPlanes/plane6.png]],Shadow = [[Planes/Shadow/plane6_shadow.png]],},
	[7]={ID = 7,Path = [[Planes/AbandonPlanes/plane7.png]],Shadow = [[Planes/Shadow/plane7_shadow.png]],},
	[8]={ID = 8,Path = [[Planes/AbandonPlanes/plane8.png]],Shadow = [[Planes/Shadow/plane8_shadow.png]],},
	[9]={ID = 9,Path = [[Planes/AbandonPlanes/plane9.png]],Shadow = [[Planes/Shadow/plane9_shadow.png]],},
	[10]={ID = 10,Path = [[Planes/AbandonPlanes/plane10.png]],Shadow = [[Planes/Shadow/plane10_shadow.png]],},
	[11]={ID = 11,Path = [[Planes/AbandonPlanes/plane11.png]],Shadow = [[Planes/Shadow/plane11_shadow.png]],},
	[12]={ID = 12,Path = [[Planes/AbandonPlanes/plane12.png]],Shadow = [[Planes/Shadow/plane12_shadow.png]],},
	[13]={ID = 13,Path = [[Planes/AbandonPlanes/plane13.png]],Shadow = [[Planes/Shadow/plane13_shadow.png]],},
	[14]={ID = 14,Path = [[Planes/AbandonPlanes/plane14.png]],Shadow = [[Planes/Shadow/plane14_shadow.png]],},
	[15]={ID = 15,Path = [[Planes/AbandonPlanes/plane15.png]],Shadow = [[Planes/Shadow/plane15_shadow.png]],},
	[16]={ID = 16,Path = [[Planes/AbandonPlanes/plane16.png]],Shadow = [[Planes/Shadow/plane16_shadow.png]],},
}

LuaExcelManager.scene_boom = {
	[1]={ID = 1,Path = [[Planes/Boom/boom.png]],},
	[2]={ID = 2,Path = [[Planes/Boom/Energyboom.png]],},
	[3]={ID = 3,Path = [[Planes/Boom/testboom.png]],},
}
