//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SDK_Lib_XmlItemBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SDK.Lib.XmlItemBase), typeof(System.Object));
		L.RegFunction("parseXml", parseXml);
		L.RegFunction("New", _CreateSDK_Lib_XmlItemBase);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSDK_Lib_XmlItemBase(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SDK.Lib.XmlItemBase obj = new SDK.Lib.XmlItemBase();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SDK.Lib.XmlItemBase.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int parseXml(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SDK.Lib.XmlItemBase obj = (SDK.Lib.XmlItemBase)ToLua.CheckObject(L, 1, typeof(SDK.Lib.XmlItemBase));
			System.Security.SecurityElement arg0 = (System.Security.SecurityElement)ToLua.CheckObject(L, 2, typeof(System.Security.SecurityElement));
			obj.parseXml(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

