//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SDK_Lib_SelectEnterModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(SDK.Lib.SelectEnterMode));
		L.RegVar("eLoginAccount", get_eLoginAccount, null);
		L.RegVar("eCreateAccount", get_eCreateAccount, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eLoginAccount(IntPtr L)
	{
		ToLua.Push(L, SDK.Lib.SelectEnterMode.eLoginAccount);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eCreateAccount(IntPtr L)
	{
		ToLua.Push(L, SDK.Lib.SelectEnterMode.eCreateAccount);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		SDK.Lib.SelectEnterMode o = (SDK.Lib.SelectEnterMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

