//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SDK_Lib_GlobalEventCmdWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SDK.Lib.GlobalEventCmd), typeof(System.Object));
		L.RegFunction("onSample", onSample);
		L.RegFunction("onEnterWorld", onEnterWorld);
		L.RegFunction("New", _CreateSDK_Lib_GlobalEventCmd);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSDK_Lib_GlobalEventCmd(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SDK.Lib.GlobalEventCmd obj = new SDK.Lib.GlobalEventCmd();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SDK.Lib.GlobalEventCmd.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onSample(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			SDK.Lib.GlobalEventCmd.onSample();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onEnterWorld(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			SDK.Lib.GlobalEventCmd.onEnterWorld();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

