//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SDK_Lib_PlayerMainWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SDK.Lib.PlayerMain), typeof(SDK.Lib.Player));
		L.RegFunction("initRender", initRender);
		L.RegFunction("dispose", dispose);
		L.RegFunction("autoHandle", autoHandle);
		L.RegFunction("emitSnowBlock", emitSnowBlock);
		L.RegFunction("setName", setName);
		L.RegFunction("onChildChanged", onChildChanged);
		L.RegFunction("onChildMassChanged", onChildMassChanged);
		L.RegFunction("moveForwardByOrient", moveForwardByOrient);
		L.RegFunction("onPressButNoMove", onPressButNoMove);
		L.RegFunction("stopMove", stopMove);
		L.RegFunction("New", _CreateSDK_Lib_PlayerMain);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSDK_Lib_PlayerMain(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SDK.Lib.PlayerMain obj = new SDK.Lib.PlayerMain();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SDK.Lib.PlayerMain.New");
			}
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int initRender(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			obj.initRender();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			obj.dispose();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int autoHandle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			obj.autoHandle();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int emitSnowBlock(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			obj.emitSnowBlock();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			string arg0 = ToLua.CheckString(L, 2);
			obj.setName(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onChildChanged(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			obj.onChildChanged();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onChildMassChanged(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			SDK.Lib.IDispatchObject arg0 = (SDK.Lib.IDispatchObject)ToLua.CheckObject(L, 2, typeof(SDK.Lib.IDispatchObject));
			obj.onChildMassChanged(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int moveForwardByOrient(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			UnityEngine.Vector2 arg0 = ToLua.ToVector2(L, 2);
			obj.moveForwardByOrient(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int onPressButNoMove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			obj.onPressButNoMove();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int stopMove(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SDK.Lib.PlayerMain obj = (SDK.Lib.PlayerMain)ToLua.CheckObject(L, 1, typeof(SDK.Lib.PlayerMain));
			obj.stopMove();
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

