// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object.proto

#ifndef PROTOBUF_object_2eproto__INCLUDED
#define PROTOBUF_object_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace svr {
class AllObjSerialize;
class AllObjSerializeDefaultTypeInternal;
extern AllObjSerializeDefaultTypeInternal _AllObjSerialize_default_instance_;
class AllSkinSerialize;
class AllSkinSerializeDefaultTypeInternal;
extern AllSkinSerializeDefaultTypeInternal _AllSkinSerialize_default_instance_;
class AllVarSerialize;
class AllVarSerializeDefaultTypeInternal;
extern AllVarSerializeDefaultTypeInternal _AllVarSerialize_default_instance_;
class OneBullet;
class OneBulletDefaultTypeInternal;
extern OneBulletDefaultTypeInternal _OneBullet_default_instance_;
class OneObjSerialize;
class OneObjSerializeDefaultTypeInternal;
extern OneObjSerializeDefaultTypeInternal _OneObjSerialize_default_instance_;
class OneSkinSerialize;
class OneSkinSerializeDefaultTypeInternal;
extern OneSkinSerializeDefaultTypeInternal _OneSkinSerialize_default_instance_;
class OneVar;
class OneVarDefaultTypeInternal;
extern OneVarDefaultTypeInternal _OneVar_default_instance_;
}  // namespace svr

namespace svr {

namespace protobuf_object_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_object_2eproto

// ===================================================================

class OneObjSerialize : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svr.OneObjSerialize) */ {
 public:
  OneObjSerialize();
  virtual ~OneObjSerialize();

  OneObjSerialize(const OneObjSerialize& from);

  inline OneObjSerialize& operator=(const OneObjSerialize& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OneObjSerialize& default_instance();

  static inline const OneObjSerialize* internal_default_instance() {
    return reinterpret_cast<const OneObjSerialize*>(
               &_OneObjSerialize_default_instance_);
  }

  void Swap(OneObjSerialize* other);

  // implements Message ----------------------------------------------

  inline OneObjSerialize* New() const PROTOBUF_FINAL { return New(NULL); }

  OneObjSerialize* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OneObjSerialize& from);
  void MergeFrom(const OneObjSerialize& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OneObjSerialize* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 uid = 2;
  void clear_uid();
  static const int kUidFieldNumber = 2;
  ::google::protobuf::uint64 uid() const;
  void set_uid(::google::protobuf::uint64 value);

  // uint32 baseid = 1;
  void clear_baseid();
  static const int kBaseidFieldNumber = 1;
  ::google::protobuf::uint32 baseid() const;
  void set_baseid(::google::protobuf::uint32 value);

  // uint32 num = 3;
  void clear_num();
  static const int kNumFieldNumber = 3;
  ::google::protobuf::uint32 num() const;
  void set_num(::google::protobuf::uint32 value);

  // uint32 bind = 4;
  void clear_bind();
  static const int kBindFieldNumber = 4;
  ::google::protobuf::uint32 bind() const;
  void set_bind(::google::protobuf::uint32 value);

  // uint32 upgrade = 5;
  void clear_upgrade();
  static const int kUpgradeFieldNumber = 5;
  ::google::protobuf::uint32 upgrade() const;
  void set_upgrade(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:svr.OneObjSerialize)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 uid_;
  ::google::protobuf::uint32 baseid_;
  ::google::protobuf::uint32 num_;
  ::google::protobuf::uint32 bind_;
  ::google::protobuf::uint32 upgrade_;
  mutable int _cached_size_;
  friend struct  protobuf_object_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AllObjSerialize : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svr.AllObjSerialize) */ {
 public:
  AllObjSerialize();
  virtual ~AllObjSerialize();

  AllObjSerialize(const AllObjSerialize& from);

  inline AllObjSerialize& operator=(const AllObjSerialize& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AllObjSerialize& default_instance();

  static inline const AllObjSerialize* internal_default_instance() {
    return reinterpret_cast<const AllObjSerialize*>(
               &_AllObjSerialize_default_instance_);
  }

  void Swap(AllObjSerialize* other);

  // implements Message ----------------------------------------------

  inline AllObjSerialize* New() const PROTOBUF_FINAL { return New(NULL); }

  AllObjSerialize* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AllObjSerialize& from);
  void MergeFrom(const AllObjSerialize& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AllObjSerialize* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .svr.OneObjSerialize objs = 1;
  int objs_size() const;
  void clear_objs();
  static const int kObjsFieldNumber = 1;
  const ::svr::OneObjSerialize& objs(int index) const;
  ::svr::OneObjSerialize* mutable_objs(int index);
  ::svr::OneObjSerialize* add_objs();
  ::google::protobuf::RepeatedPtrField< ::svr::OneObjSerialize >*
      mutable_objs();
  const ::google::protobuf::RepeatedPtrField< ::svr::OneObjSerialize >&
      objs() const;

  // @@protoc_insertion_point(class_scope:svr.AllObjSerialize)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::svr::OneObjSerialize > objs_;
  mutable int _cached_size_;
  friend struct  protobuf_object_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OneSkinSerialize : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svr.OneSkinSerialize) */ {
 public:
  OneSkinSerialize();
  virtual ~OneSkinSerialize();

  OneSkinSerialize(const OneSkinSerialize& from);

  inline OneSkinSerialize& operator=(const OneSkinSerialize& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OneSkinSerialize& default_instance();

  static inline const OneSkinSerialize* internal_default_instance() {
    return reinterpret_cast<const OneSkinSerialize*>(
               &_OneSkinSerialize_default_instance_);
  }

  void Swap(OneSkinSerialize* other);

  // implements Message ----------------------------------------------

  inline OneSkinSerialize* New() const PROTOBUF_FINAL { return New(NULL); }

  OneSkinSerialize* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OneSkinSerialize& from);
  void MergeFrom(const OneSkinSerialize& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OneSkinSerialize* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 index = 1;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::uint32 index() const;
  void set_index(::google::protobuf::uint32 value);

  // uint32 disappear_ts = 2;
  void clear_disappear_ts();
  static const int kDisappearTsFieldNumber = 2;
  ::google::protobuf::uint32 disappear_ts() const;
  void set_disappear_ts(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:svr.OneSkinSerialize)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 index_;
  ::google::protobuf::uint32 disappear_ts_;
  mutable int _cached_size_;
  friend struct  protobuf_object_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OneBullet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svr.OneBullet) */ {
 public:
  OneBullet();
  virtual ~OneBullet();

  OneBullet(const OneBullet& from);

  inline OneBullet& operator=(const OneBullet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OneBullet& default_instance();

  static inline const OneBullet* internal_default_instance() {
    return reinterpret_cast<const OneBullet*>(
               &_OneBullet_default_instance_);
  }

  void Swap(OneBullet* other);

  // implements Message ----------------------------------------------

  inline OneBullet* New() const PROTOBUF_FINAL { return New(NULL); }

  OneBullet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OneBullet& from);
  void MergeFrom(const OneBullet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OneBullet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 objid = 1;
  void clear_objid();
  static const int kObjidFieldNumber = 1;
  ::google::protobuf::uint32 objid() const;
  void set_objid(::google::protobuf::uint32 value);

  // uint32 disappear_ts = 2;
  void clear_disappear_ts();
  static const int kDisappearTsFieldNumber = 2;
  ::google::protobuf::uint32 disappear_ts() const;
  void set_disappear_ts(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:svr.OneBullet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 objid_;
  ::google::protobuf::uint32 disappear_ts_;
  mutable int _cached_size_;
  friend struct  protobuf_object_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AllSkinSerialize : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svr.AllSkinSerialize) */ {
 public:
  AllSkinSerialize();
  virtual ~AllSkinSerialize();

  AllSkinSerialize(const AllSkinSerialize& from);

  inline AllSkinSerialize& operator=(const AllSkinSerialize& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AllSkinSerialize& default_instance();

  static inline const AllSkinSerialize* internal_default_instance() {
    return reinterpret_cast<const AllSkinSerialize*>(
               &_AllSkinSerialize_default_instance_);
  }

  void Swap(AllSkinSerialize* other);

  // implements Message ----------------------------------------------

  inline AllSkinSerialize* New() const PROTOBUF_FINAL { return New(NULL); }

  AllSkinSerialize* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AllSkinSerialize& from);
  void MergeFrom(const AllSkinSerialize& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AllSkinSerialize* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .svr.OneSkinSerialize skins = 2;
  int skins_size() const;
  void clear_skins();
  static const int kSkinsFieldNumber = 2;
  const ::svr::OneSkinSerialize& skins(int index) const;
  ::svr::OneSkinSerialize* mutable_skins(int index);
  ::svr::OneSkinSerialize* add_skins();
  ::google::protobuf::RepeatedPtrField< ::svr::OneSkinSerialize >*
      mutable_skins();
  const ::google::protobuf::RepeatedPtrField< ::svr::OneSkinSerialize >&
      skins() const;

  // repeated .svr.OneBullet bullets = 4;
  int bullets_size() const;
  void clear_bullets();
  static const int kBulletsFieldNumber = 4;
  const ::svr::OneBullet& bullets(int index) const;
  ::svr::OneBullet* mutable_bullets(int index);
  ::svr::OneBullet* add_bullets();
  ::google::protobuf::RepeatedPtrField< ::svr::OneBullet >*
      mutable_bullets();
  const ::google::protobuf::RepeatedPtrField< ::svr::OneBullet >&
      bullets() const;

  // uint32 default_skinid = 1;
  void clear_default_skinid();
  static const int kDefaultSkinidFieldNumber = 1;
  ::google::protobuf::uint32 default_skinid() const;
  void set_default_skinid(::google::protobuf::uint32 value);

  // uint32 default_bullet = 3;
  void clear_default_bullet();
  static const int kDefaultBulletFieldNumber = 3;
  ::google::protobuf::uint32 default_bullet() const;
  void set_default_bullet(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:svr.AllSkinSerialize)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::svr::OneSkinSerialize > skins_;
  ::google::protobuf::RepeatedPtrField< ::svr::OneBullet > bullets_;
  ::google::protobuf::uint32 default_skinid_;
  ::google::protobuf::uint32 default_bullet_;
  mutable int _cached_size_;
  friend struct  protobuf_object_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class OneVar : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svr.OneVar) */ {
 public:
  OneVar();
  virtual ~OneVar();

  OneVar(const OneVar& from);

  inline OneVar& operator=(const OneVar& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OneVar& default_instance();

  static inline const OneVar* internal_default_instance() {
    return reinterpret_cast<const OneVar*>(
               &_OneVar_default_instance_);
  }

  void Swap(OneVar* other);

  // implements Message ----------------------------------------------

  inline OneVar* New() const PROTOBUF_FINAL { return New(NULL); }

  OneVar* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OneVar& from);
  void MergeFrom(const OneVar& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OneVar* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::uint64 value() const;
  void set_value(::google::protobuf::uint64 value);

  // uint32 varid = 1;
  void clear_varid();
  static const int kVaridFieldNumber = 1;
  ::google::protobuf::uint32 varid() const;
  void set_varid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:svr.OneVar)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 value_;
  ::google::protobuf::uint32 varid_;
  mutable int _cached_size_;
  friend struct  protobuf_object_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AllVarSerialize : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:svr.AllVarSerialize) */ {
 public:
  AllVarSerialize();
  virtual ~AllVarSerialize();

  AllVarSerialize(const AllVarSerialize& from);

  inline AllVarSerialize& operator=(const AllVarSerialize& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AllVarSerialize& default_instance();

  static inline const AllVarSerialize* internal_default_instance() {
    return reinterpret_cast<const AllVarSerialize*>(
               &_AllVarSerialize_default_instance_);
  }

  void Swap(AllVarSerialize* other);

  // implements Message ----------------------------------------------

  inline AllVarSerialize* New() const PROTOBUF_FINAL { return New(NULL); }

  AllVarSerialize* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AllVarSerialize& from);
  void MergeFrom(const AllVarSerialize& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AllVarSerialize* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .svr.OneVar vars = 1;
  int vars_size() const;
  void clear_vars();
  static const int kVarsFieldNumber = 1;
  const ::svr::OneVar& vars(int index) const;
  ::svr::OneVar* mutable_vars(int index);
  ::svr::OneVar* add_vars();
  ::google::protobuf::RepeatedPtrField< ::svr::OneVar >*
      mutable_vars();
  const ::google::protobuf::RepeatedPtrField< ::svr::OneVar >&
      vars() const;

  // @@protoc_insertion_point(class_scope:svr.AllVarSerialize)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::svr::OneVar > vars_;
  mutable int _cached_size_;
  friend struct  protobuf_object_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// OneObjSerialize

// uint32 baseid = 1;
inline void OneObjSerialize::clear_baseid() {
  baseid_ = 0u;
}
inline ::google::protobuf::uint32 OneObjSerialize::baseid() const {
  // @@protoc_insertion_point(field_get:svr.OneObjSerialize.baseid)
  return baseid_;
}
inline void OneObjSerialize::set_baseid(::google::protobuf::uint32 value) {
  
  baseid_ = value;
  // @@protoc_insertion_point(field_set:svr.OneObjSerialize.baseid)
}

// uint64 uid = 2;
inline void OneObjSerialize::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OneObjSerialize::uid() const {
  // @@protoc_insertion_point(field_get:svr.OneObjSerialize.uid)
  return uid_;
}
inline void OneObjSerialize::set_uid(::google::protobuf::uint64 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:svr.OneObjSerialize.uid)
}

// uint32 num = 3;
inline void OneObjSerialize::clear_num() {
  num_ = 0u;
}
inline ::google::protobuf::uint32 OneObjSerialize::num() const {
  // @@protoc_insertion_point(field_get:svr.OneObjSerialize.num)
  return num_;
}
inline void OneObjSerialize::set_num(::google::protobuf::uint32 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:svr.OneObjSerialize.num)
}

// uint32 bind = 4;
inline void OneObjSerialize::clear_bind() {
  bind_ = 0u;
}
inline ::google::protobuf::uint32 OneObjSerialize::bind() const {
  // @@protoc_insertion_point(field_get:svr.OneObjSerialize.bind)
  return bind_;
}
inline void OneObjSerialize::set_bind(::google::protobuf::uint32 value) {
  
  bind_ = value;
  // @@protoc_insertion_point(field_set:svr.OneObjSerialize.bind)
}

// uint32 upgrade = 5;
inline void OneObjSerialize::clear_upgrade() {
  upgrade_ = 0u;
}
inline ::google::protobuf::uint32 OneObjSerialize::upgrade() const {
  // @@protoc_insertion_point(field_get:svr.OneObjSerialize.upgrade)
  return upgrade_;
}
inline void OneObjSerialize::set_upgrade(::google::protobuf::uint32 value) {
  
  upgrade_ = value;
  // @@protoc_insertion_point(field_set:svr.OneObjSerialize.upgrade)
}

// -------------------------------------------------------------------

// AllObjSerialize

// repeated .svr.OneObjSerialize objs = 1;
inline int AllObjSerialize::objs_size() const {
  return objs_.size();
}
inline void AllObjSerialize::clear_objs() {
  objs_.Clear();
}
inline const ::svr::OneObjSerialize& AllObjSerialize::objs(int index) const {
  // @@protoc_insertion_point(field_get:svr.AllObjSerialize.objs)
  return objs_.Get(index);
}
inline ::svr::OneObjSerialize* AllObjSerialize::mutable_objs(int index) {
  // @@protoc_insertion_point(field_mutable:svr.AllObjSerialize.objs)
  return objs_.Mutable(index);
}
inline ::svr::OneObjSerialize* AllObjSerialize::add_objs() {
  // @@protoc_insertion_point(field_add:svr.AllObjSerialize.objs)
  return objs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::svr::OneObjSerialize >*
AllObjSerialize::mutable_objs() {
  // @@protoc_insertion_point(field_mutable_list:svr.AllObjSerialize.objs)
  return &objs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::svr::OneObjSerialize >&
AllObjSerialize::objs() const {
  // @@protoc_insertion_point(field_list:svr.AllObjSerialize.objs)
  return objs_;
}

// -------------------------------------------------------------------

// OneSkinSerialize

// uint32 index = 1;
inline void OneSkinSerialize::clear_index() {
  index_ = 0u;
}
inline ::google::protobuf::uint32 OneSkinSerialize::index() const {
  // @@protoc_insertion_point(field_get:svr.OneSkinSerialize.index)
  return index_;
}
inline void OneSkinSerialize::set_index(::google::protobuf::uint32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:svr.OneSkinSerialize.index)
}

// uint32 disappear_ts = 2;
inline void OneSkinSerialize::clear_disappear_ts() {
  disappear_ts_ = 0u;
}
inline ::google::protobuf::uint32 OneSkinSerialize::disappear_ts() const {
  // @@protoc_insertion_point(field_get:svr.OneSkinSerialize.disappear_ts)
  return disappear_ts_;
}
inline void OneSkinSerialize::set_disappear_ts(::google::protobuf::uint32 value) {
  
  disappear_ts_ = value;
  // @@protoc_insertion_point(field_set:svr.OneSkinSerialize.disappear_ts)
}

// -------------------------------------------------------------------

// OneBullet

// uint32 objid = 1;
inline void OneBullet::clear_objid() {
  objid_ = 0u;
}
inline ::google::protobuf::uint32 OneBullet::objid() const {
  // @@protoc_insertion_point(field_get:svr.OneBullet.objid)
  return objid_;
}
inline void OneBullet::set_objid(::google::protobuf::uint32 value) {
  
  objid_ = value;
  // @@protoc_insertion_point(field_set:svr.OneBullet.objid)
}

// uint32 disappear_ts = 2;
inline void OneBullet::clear_disappear_ts() {
  disappear_ts_ = 0u;
}
inline ::google::protobuf::uint32 OneBullet::disappear_ts() const {
  // @@protoc_insertion_point(field_get:svr.OneBullet.disappear_ts)
  return disappear_ts_;
}
inline void OneBullet::set_disappear_ts(::google::protobuf::uint32 value) {
  
  disappear_ts_ = value;
  // @@protoc_insertion_point(field_set:svr.OneBullet.disappear_ts)
}

// -------------------------------------------------------------------

// AllSkinSerialize

// uint32 default_skinid = 1;
inline void AllSkinSerialize::clear_default_skinid() {
  default_skinid_ = 0u;
}
inline ::google::protobuf::uint32 AllSkinSerialize::default_skinid() const {
  // @@protoc_insertion_point(field_get:svr.AllSkinSerialize.default_skinid)
  return default_skinid_;
}
inline void AllSkinSerialize::set_default_skinid(::google::protobuf::uint32 value) {
  
  default_skinid_ = value;
  // @@protoc_insertion_point(field_set:svr.AllSkinSerialize.default_skinid)
}

// repeated .svr.OneSkinSerialize skins = 2;
inline int AllSkinSerialize::skins_size() const {
  return skins_.size();
}
inline void AllSkinSerialize::clear_skins() {
  skins_.Clear();
}
inline const ::svr::OneSkinSerialize& AllSkinSerialize::skins(int index) const {
  // @@protoc_insertion_point(field_get:svr.AllSkinSerialize.skins)
  return skins_.Get(index);
}
inline ::svr::OneSkinSerialize* AllSkinSerialize::mutable_skins(int index) {
  // @@protoc_insertion_point(field_mutable:svr.AllSkinSerialize.skins)
  return skins_.Mutable(index);
}
inline ::svr::OneSkinSerialize* AllSkinSerialize::add_skins() {
  // @@protoc_insertion_point(field_add:svr.AllSkinSerialize.skins)
  return skins_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::svr::OneSkinSerialize >*
AllSkinSerialize::mutable_skins() {
  // @@protoc_insertion_point(field_mutable_list:svr.AllSkinSerialize.skins)
  return &skins_;
}
inline const ::google::protobuf::RepeatedPtrField< ::svr::OneSkinSerialize >&
AllSkinSerialize::skins() const {
  // @@protoc_insertion_point(field_list:svr.AllSkinSerialize.skins)
  return skins_;
}

// uint32 default_bullet = 3;
inline void AllSkinSerialize::clear_default_bullet() {
  default_bullet_ = 0u;
}
inline ::google::protobuf::uint32 AllSkinSerialize::default_bullet() const {
  // @@protoc_insertion_point(field_get:svr.AllSkinSerialize.default_bullet)
  return default_bullet_;
}
inline void AllSkinSerialize::set_default_bullet(::google::protobuf::uint32 value) {
  
  default_bullet_ = value;
  // @@protoc_insertion_point(field_set:svr.AllSkinSerialize.default_bullet)
}

// repeated .svr.OneBullet bullets = 4;
inline int AllSkinSerialize::bullets_size() const {
  return bullets_.size();
}
inline void AllSkinSerialize::clear_bullets() {
  bullets_.Clear();
}
inline const ::svr::OneBullet& AllSkinSerialize::bullets(int index) const {
  // @@protoc_insertion_point(field_get:svr.AllSkinSerialize.bullets)
  return bullets_.Get(index);
}
inline ::svr::OneBullet* AllSkinSerialize::mutable_bullets(int index) {
  // @@protoc_insertion_point(field_mutable:svr.AllSkinSerialize.bullets)
  return bullets_.Mutable(index);
}
inline ::svr::OneBullet* AllSkinSerialize::add_bullets() {
  // @@protoc_insertion_point(field_add:svr.AllSkinSerialize.bullets)
  return bullets_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::svr::OneBullet >*
AllSkinSerialize::mutable_bullets() {
  // @@protoc_insertion_point(field_mutable_list:svr.AllSkinSerialize.bullets)
  return &bullets_;
}
inline const ::google::protobuf::RepeatedPtrField< ::svr::OneBullet >&
AllSkinSerialize::bullets() const {
  // @@protoc_insertion_point(field_list:svr.AllSkinSerialize.bullets)
  return bullets_;
}

// -------------------------------------------------------------------

// OneVar

// uint32 varid = 1;
inline void OneVar::clear_varid() {
  varid_ = 0u;
}
inline ::google::protobuf::uint32 OneVar::varid() const {
  // @@protoc_insertion_point(field_get:svr.OneVar.varid)
  return varid_;
}
inline void OneVar::set_varid(::google::protobuf::uint32 value) {
  
  varid_ = value;
  // @@protoc_insertion_point(field_set:svr.OneVar.varid)
}

// uint64 value = 2;
inline void OneVar::clear_value() {
  value_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 OneVar::value() const {
  // @@protoc_insertion_point(field_get:svr.OneVar.value)
  return value_;
}
inline void OneVar::set_value(::google::protobuf::uint64 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:svr.OneVar.value)
}

// -------------------------------------------------------------------

// AllVarSerialize

// repeated .svr.OneVar vars = 1;
inline int AllVarSerialize::vars_size() const {
  return vars_.size();
}
inline void AllVarSerialize::clear_vars() {
  vars_.Clear();
}
inline const ::svr::OneVar& AllVarSerialize::vars(int index) const {
  // @@protoc_insertion_point(field_get:svr.AllVarSerialize.vars)
  return vars_.Get(index);
}
inline ::svr::OneVar* AllVarSerialize::mutable_vars(int index) {
  // @@protoc_insertion_point(field_mutable:svr.AllVarSerialize.vars)
  return vars_.Mutable(index);
}
inline ::svr::OneVar* AllVarSerialize::add_vars() {
  // @@protoc_insertion_point(field_add:svr.AllVarSerialize.vars)
  return vars_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::svr::OneVar >*
AllVarSerialize::mutable_vars() {
  // @@protoc_insertion_point(field_mutable_list:svr.AllVarSerialize.vars)
  return &vars_;
}
inline const ::google::protobuf::RepeatedPtrField< ::svr::OneVar >&
AllVarSerialize::vars() const {
  // @@protoc_insertion_point(field_list:svr.AllVarSerialize.vars)
  return vars_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace svr

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_object_2eproto__INCLUDED
